-- Supabase SQL setup (safe to re-run)

-- Core call logs table
CREATE TABLE IF NOT EXISTS call_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    phone_number TEXT,
    duration_seconds INTEGER,
    transcript TEXT,
    summary TEXT
);

ALTER TABLE call_logs ADD COLUMN IF NOT EXISTS recording_url TEXT;
ALTER TABLE call_logs ADD COLUMN IF NOT EXISTS caller_name TEXT;
ALTER TABLE call_logs ADD COLUMN IF NOT EXISTS sentiment TEXT;
ALTER TABLE call_logs ADD COLUMN IF NOT EXISTS estimated_cost_usd NUMERIC(10,5);
ALTER TABLE call_logs ADD COLUMN IF NOT EXISTS call_date DATE;
ALTER TABLE call_logs ADD COLUMN IF NOT EXISTS call_hour INTEGER;
ALTER TABLE call_logs ADD COLUMN IF NOT EXISTS call_day_of_week TEXT;
ALTER TABLE call_logs ADD COLUMN IF NOT EXISTS was_booked BOOLEAN DEFAULT FALSE;
ALTER TABLE call_logs ADD COLUMN IF NOT EXISTS interrupt_count INTEGER DEFAULT 0;
ALTER TABLE call_logs ADD COLUMN IF NOT EXISTS call_purpose TEXT;
ALTER TABLE call_logs ADD COLUMN IF NOT EXISTS call_summary TEXT;
ALTER TABLE call_logs ADD COLUMN IF NOT EXISTS appointment_time TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_call_logs_phone ON call_logs (phone_number);
CREATE INDEX IF NOT EXISTS idx_call_logs_created_at ON call_logs (created_at DESC);

ALTER TABLE call_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all actions for service role" ON call_logs;
CREATE POLICY "Enable all actions for service role" ON call_logs FOR ALL USING (true) WITH CHECK (true);

-- Real-time transcript table
CREATE TABLE IF NOT EXISTS call_transcripts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    call_room_id TEXT NOT NULL,
    phone TEXT,
    role TEXT CHECK (role IN ('user', 'assistant')),
    content TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_call_transcripts_room ON call_transcripts (call_room_id);
CREATE INDEX IF NOT EXISTS idx_call_transcripts_phone ON call_transcripts (phone);

ALTER TABLE call_transcripts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon insert transcripts" ON call_transcripts;
CREATE POLICY "Allow anon insert transcripts" ON call_transcripts FOR INSERT TO anon WITH CHECK (true);
DROP POLICY IF EXISTS "Allow anon select transcripts" ON call_transcripts;
CREATE POLICY "Allow anon select transcripts" ON call_transcripts FOR SELECT TO anon USING (true);

-- Active call tracking table
CREATE TABLE IF NOT EXISTS active_calls (
    room_id TEXT PRIMARY KEY,
    phone TEXT,
    caller_name TEXT,
    status TEXT DEFAULT 'ringing',
    started_at TIMESTAMPTZ DEFAULT NOW(),
    last_updated TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE active_calls ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon all active_calls" ON active_calls;
CREATE POLICY "Allow anon all active_calls"
    ON active_calls FOR ALL TO anon USING (true) WITH CHECK (true);
